# Generated by Django 3.1.6 on 2021-02-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0003_auto_20210228_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentplace',
            old_name='payment_mode',
            new_name='payment',
        ),
    ]
