# Generated by Django 3.1.6 on 2021-02-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0008_auto_20210228_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentplace',
            name='district',
        ),
        migrations.AddField(
            model_name='rentplace',
            name='district',
            field=models.ManyToManyField(to='renting.District'),
        ),
    ]
