# Generated by Django 3.1.6 on 2021-03-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0010_auto_20210307_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentplace',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='rentplace',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='rentplace',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='rentplace',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='rentplace',
            name='image_5',
        ),
        migrations.AlterField(
            model_name='rentplace',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
