# Generated by Django 3.1.6 on 2021-03-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0011_auto_20210307_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentplace',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
