# Generated by Django 3.1.6 on 2021-03-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0012_auto_20210307_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentplace',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rentplace',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
