# Generated by Django 3.1.6 on 2021-03-27 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0013_auto_20210327_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentplace',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
