# Generated by Django 3.1.6 on 2021-02-28 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('document', models.CharField(max_length=9)),
                ('business_name', models.CharField(max_length=200)),
                ('business_address', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=200)),
                ('business_products', models.CharField(max_length=200)),
                ('business_references', models.CharField(max_length=200)),
                ('business_description', models.TextField()),
                ('profile_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
