# Generated by Django 3.1.6 on 2021-03-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0013_auto_20210327_1104'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinfo',
            name='business_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renting.district'),
        ),
        migrations.AddField(
            model_name='partnerinfo',
            name='ruc',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='partnerinfo',
            name='document',
            field=models.CharField(max_length=200),
        ),
    ]
