# Generated by Django 3.1.6 on 2021-03-07 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0012_auto_20210307_1634'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinfo',
            name='business_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renting.district'),
        ),
    ]
