# Generated by Django 3.1.6 on 2021-03-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partnerinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinfo',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
