# Generated by Django 3.1.6 on 2021-03-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20210314_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinfo',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
