# Generated by Django 3.1.6 on 2021-03-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20210314_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerinfo',
            old_name='username',
            new_name='user_name',
        ),
    ]
