# Generated by Django 3.1.6 on 2021-03-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20210314_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerinfo',
            name='user_name',
        ),
    ]
